version: "3.7"

services:
    client:
      build: ./client
      restart: always
      ports:
        - "3030:3000"
      volumes:
        - ./client:/client
        - /client/node_modules
      links:
        - api
      networks:
        - webappnetwork
    api:
      build: ./api
      restart: always
      ports:
        - "8080:8080"
      volumes:
        - ./api:/api
        - /api/node_modules
      depends_on:
        - db
      networks:
        - webappnetwork
    db:
      image: mysql:5.7
      volumes:
        - ./db/mysql_data:/var/lib/mysql
      restart: always
      ports:
        - "3333:3306"
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: docker_test
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      networks:
        - webappnetwork

networks:
  webappnetwork:
      driver: bridge

volumes:
  db_data: {}